#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=root
server.port=8081

#spring security
spring.security.user.name=rajesh
spring.security.user.password=1221